name: Upload Python Package on pypi

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build release distributions
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry config virtualenvs.create false
          poetry self update
          poetry install
          poetry self add poetry-plugin-shell
          poetry shell
          poetry check
          poetry cache clear PyPI --all
          poetry build
